### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by luinbytes** [IBMESP/Backpacks#3]
**Describe the bug**
Error being thrown when trying to open the AnvilUI during backpack deletion.

**Versions (please complete the following information):**
 - Minecraft Server Version: 1.21
 - Plugin Version: v2.2.2

**Pastebin any errors in console**
Link: https://pastebin.com/Uc0wTB3M

**Issue**
Everything else works fine, but when I go to remove a backpack, it tries to, the UI where you pick the backpack to remove flashes and the error in the pastebin gets thrown in the server console. Java is not my area at all so I can't make much sense of it.

**Screenshots**
Can provide if needed, unsure of what to show.

**Comment by IBMESP** [comment]
I dont have planed to solve this issue for now. I'm too busy to work on my minecraft plugins.
If you want to use this plugin you can compile the code, just use the geyser-experimental branch.
If you have no idea then add me on discord and i can provide you with the .jar file (ib.dev)
